import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, Hash, RotateCcw, X } from 'lucide-react';
import { sounds } from '@/lib/sound';
import type { GameProps } from './registry';

type Level = 'easy' | 'medium' | 'hard';
type Op = '+' | '−' | '×' | '÷';
type Phase = 'idle' | 'running' | 'done';

interface Question { text: string; answer: number; options: number[] }
interface Tally { correct: number; wrong: number; streak: number; best: number }
interface LevelSpec { label: string; hint: string; ops: readonly Op[]; /** Operand ceiling. Never used as a divisor directly. */ max: number }

const LEVELS: Record<Level, LevelSpec> = {
  easy: { label: 'Easy', hint: 'Add and subtract small numbers', ops: ['+', '−'], max: 20 },
  medium: { label: 'Medium', hint: 'Times tables up to twelve', ops: ['+', '−', '×'], max: 12 },
  hard: { label: 'Hard', hint: 'Division and negative results', ops: ['+', '−', '×', '÷'], max: 14 },
};

const ROUND_MS = 30_000;
const REVEAL_MS = 750;
const KEYS = ['1', '2', '3', '4'];
/** Non-zero, distinct offsets: the first four of these always fill the grid. */
const SPREAD = [1, -1, 2, -2, 3, -3, 4, -4, 5, -5, 6, -6];
const ZERO: Tally = { correct: 0, wrong: 0, streak: 0, best: 0 };

function rand(min: number, max: number): number {
  return min + Math.floor(Math.random() * (max - min + 1));
}

function shuffle<T>(items: T[]): T[] {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/**
 * One question with four distinct options. Division is generated by multiplying
 * a quotient with a divisor of 2 or more, so the answer is always an integer
 * and the divisor is never zero; the other operators are integer arithmetic, and
 * the distractors are the answer offset by non-zero integers. Only the hard tier
 * may subtract into negative territory.
 */
function makeQuestion(level: Level): Question {
  const spec = LEVELS[level];
  const op = spec.ops[rand(0, spec.ops.length - 1)];
  let text: string;
  let answer: number;
  if (op === '÷') {
    const divisor = rand(2, Math.min(6, spec.max));
    const quotient = rand(2, spec.max);
    text = `${divisor * quotient} ÷ ${divisor}`;
    answer = quotient;
  } else {
    const a = rand(2, spec.max);
    let b = rand(2, spec.max);
    if (op === '−' && b > a && level !== 'hard') b = rand(2, a);
    text = `${a} ${op} ${b}`;
    answer = op === '+' ? a + b : op === '−' ? a - b : a * b;
  }

  const options = [answer];
  for (const delta of SPREAD) {
    if (options.length === 4) break;
    const candidate = answer + delta;
    if (!options.includes(candidate)) options.push(candidate);
  }
  return { text, answer, options: shuffle(options) };
}

function prefersReducedMotion(): boolean {
  return typeof window !== 'undefined' && typeof window.matchMedia === 'function'
    && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

export default function MathSprint({ onScore }: GameProps) {
  const [level, setLevel] = useState<Level>('easy');
  const [phase, setPhase] = useState<Phase>('idle');
  const [question, setQuestion] = useState<Question>(() => makeQuestion('easy'));
  const [left, setLeft] = useState(ROUND_MS);
  const [tally, setTally] = useState<Tally>(ZERO);
  const [reveal, setReveal] = useState<{ picked: number; answer: number } | null>(null);

  // The hot path (timer tick, reveal timeout, keydown) cannot read state without
  // going stale, so the mutable truth lives in refs and state mirrors it.
  const levelRef = useRef<Level>('easy');
  const questionRef = useRef<Question>(question);
  const runningRef = useRef(false);
  const revealRef = useRef(false);
  const deadlineRef = useRef(0);
  const tallyRef = useRef<Tally>(ZERO);
  const scored = useRef(false);
  const revealTimer = useRef<number>();

  const setCurrent = useCallback((next: Question) => {
    questionRef.current = next;
    setQuestion(next);
  }, []);

  const advance = useCallback(() => {
    window.clearTimeout(revealTimer.current);
    revealRef.current = false;
    setReveal(null);
    setCurrent(makeQuestion(levelRef.current));
  }, [setCurrent]);

  const end = useCallback(() => {
    if (!runningRef.current) return;
    runningRef.current = false;
    window.clearTimeout(revealTimer.current);
    revealRef.current = false;
    setReveal(null);
    setPhase('done');
    sounds.close();
    if (scored.current) return;
    scored.current = true;
    const run = tallyRef.current;
    onScore?.(run.correct * 100 + run.best * 25);
  }, [onScore]);
  // Driven from a deadline, not a counter, so a dropped tick or a throttled
  // background tab cannot hand the player free seconds. Reduced motion drops
  // the refresh to whole seconds instead of a smooth sweep.
  useEffect(() => {
    if (phase !== 'running') return undefined;
    const id = window.setInterval(() => {
      const remaining = deadlineRef.current - performance.now();
      if (remaining > 0) setLeft(remaining);
      else { setLeft(0); end(); }
    }, prefersReducedMotion() ? 1000 : 100);
    return () => {
      window.clearInterval(id);
      window.clearTimeout(revealTimer.current);
    };
  }, [phase, end]);
  const start = useCallback((next?: Level) => {
    const chosen = next ?? levelRef.current;
    if (next) { levelRef.current = next; setLevel(next); }
    window.clearTimeout(revealTimer.current);
    revealRef.current = false;
    tallyRef.current = ZERO;
    setTally(ZERO);
    setReveal(null);
    scored.current = false;
    setCurrent(makeQuestion(chosen));
    deadlineRef.current = performance.now() + ROUND_MS;
    setLeft(ROUND_MS);
    runningRef.current = true;
    setPhase('running');
    sounds.toggle();
  }, [setCurrent]);

  const pick = useCallback((value: number) => {
    if (!runningRef.current) return;
    const current = questionRef.current;
    // A wrong answer never locks the player out: a second press skips the
    // reveal and moves straight on to the next question.
    if (revealRef.current) { advance(); return; }
    const hit = value === current.answer;
    const run = tallyRef.current;
    const streak = hit ? run.streak + 1 : 0;
    tallyRef.current = {
      correct: run.correct + (hit ? 1 : 0),
      wrong: run.wrong + (hit ? 0 : 1),
      streak,
      best: Math.max(run.best, streak),
    };
    setTally(tallyRef.current);
    if (hit) {
      sounds.success();
      advance();
      return;
    }
    sounds.error();
    revealRef.current = true;
    setReveal({ picked: value, answer: current.answer });
    revealTimer.current = window.setTimeout(advance, REVEAL_MS);
  }, [advance]);
  // Keys 1-4 answer. Nothing calls focus(): stealing it after a keypress strips
  // the `:focus-visible` ring off the control the player just used.
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (!runningRef.current || event.metaKey || event.ctrlKey || event.altKey) return;
      const el = event.target as HTMLElement | null;
      if (el && (el.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName))) return;
      const option = questionRef.current.options[KEYS.indexOf(event.key)];
      if (option !== undefined) pick(option);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [pick]);

  const seconds = Math.ceil(left / 1000);
  const live = phase === 'running';
  const status = phase === 'done'
    ? `Time. ${tally.correct} correct, ${tally.wrong} wrong, longest streak ${tally.best}.`
    : !live ? 'Thirty seconds. Answer as many as you can — a wrong answer only costs the seconds it takes.'
      : reveal ? `${reveal.picked} is wrong. The answer is ${reveal.answer}.`
        : `${question.text}. Pick an option, or press 1 to 4.`;

  return (
    <div className="card card-sheen rounded-panel p-5">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h3 className="font-display text-sm font-bold tracking-tight text-[var(--ink)]">MathSprint</h3>
        <span className="tag"><Hash size={12} aria-hidden="true" />{LEVELS[level].hint}</span>
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-1" role="group" aria-label="Difficulty">
        {(Object.keys(LEVELS) as Level[]).map((key) => (
          <button
            key={key} type="button" aria-pressed={level === key}
            onClick={() => start(key)} onMouseEnter={() => sounds.hover()}
            className="filter-pill min-h-[44px]"
          >
            {LEVELS[key].label}
          </button>
        ))}
      </div>

      <div className="mt-3 flex items-center gap-2">
        <div role="progressbar" aria-label="Seconds remaining" aria-valuemin={0} aria-valuemax={ROUND_MS / 1000} aria-valuenow={seconds} className="progress-track flex-1">
          <div className="progress-fill transition-all duration-150 ease-linear" style={{ width: `${(left / ROUND_MS) * 100}%` }} />
        </div>
        {/* aria-hidden: the progressbar already carries the value, and a live
            ticking number would interrupt every answer. */}
        <span aria-hidden="true" className="tag w-14 justify-center font-mono">{seconds}s</span>
      </div>

      <dl className="mt-3 flex flex-wrap justify-center gap-1.5">
        {([['Correct', tally.correct], ['Wrong', tally.wrong], ['Streak', tally.streak]] as const).map(([label, value]) => (
          <div key={label} className="chip">{label} <span className="font-mono font-semibold text-[var(--ink)]">{value}</span></div>
        ))}
      </dl>

      <p role="status" aria-live="polite" className="mt-3 text-center text-xs leading-relaxed text-[var(--ink-2)]">
        {status}
      </p>

      <p aria-hidden="true" className="mt-2 text-center font-display text-3xl font-bold tracking-tight text-[var(--ink)]">
        {question.text} = ?
      </p>

      <div role="group" aria-label={`Answers for ${question.text}`} className="mt-3 grid grid-cols-2 gap-2">
        {question.options.map((option, index) => {
          const isAnswer = option === question.answer;
          const isPicked = reveal?.picked === option;
          return (
            <button
              key={option} type="button" disabled={!live} aria-keyshortcuts={KEYS[index]}
              onClick={() => pick(option)} onMouseEnter={() => sounds.hover()}
              aria-label={`${option}, press ${KEYS[index]}`}
              className={`flex min-h-[44px] items-center justify-center gap-1.5 rounded-card border text-lg font-bold transition-colors duration-[--dur-hover] disabled:opacity-60 ${
                isAnswer && reveal
                  ? 'border-[rgba(10,130,189,0.55)] bg-[var(--accent-soft)] text-[var(--accent)]'
                  : isPicked
                    ? 'border-[rgba(230,79,55,0.5)] bg-[var(--ember-soft)] text-[var(--ember)] line-through'
                    : 'border-[var(--line)] bg-[var(--surface-2)] text-[var(--ink)] hover:border-[rgba(10,130,189,0.4)] hover:bg-[var(--accent-soft)]'
              }`}
            >
              {option}
              {isAnswer && reveal && <Check size={13} aria-hidden="true" />}
              {isPicked && <X size={13} aria-hidden="true" />}
            </button>
          );
        })}
      </div>

      <button
        type="button" onClick={() => start()} onMouseEnter={() => sounds.hover()}
        className={`btn mt-4 w-full ${phase === 'idle' ? 'btn-primary' : 'btn-secondary'}`}
      >
        <RotateCcw size={15} aria-hidden="true" />
        {phase === 'done' ? 'Play again' : live ? 'Restart round' : 'Start 30s round'}
      </button>
    </div>
  );
}
